INGESTION_PARSE = "ingestion.parse"
INGESTION_METADATA = "ingestion.metadata"
INGESTION_CHUNK = "ingestion.chunk"
INGESTION_EMBED = "ingestion.embed"
INGESTION_INDEX = "ingestion.index"
RAG_LONG_QUERY = "rag.long_query"
EVAL_BATCH = "eval.batch"

RETRY_INGESTION = "retry.ingestion"
RETRY_EMBEDDING = "retry.embedding"
RETRY_INDEXING = "retry.indexing"

DLQ_INGESTION = "dlq.ingestion"
DLQ_EMBEDDING = "dlq.embedding"
DLQ_INDEXING = "dlq.indexing"
DLQ_RAG = "dlq.rag"

INGESTION_TOPICS = (
    INGESTION_PARSE,
    INGESTION_METADATA,
    INGESTION_CHUNK,
    INGESTION_EMBED,
    INGESTION_INDEX,
)

RETRY_TOPICS = (
    RETRY_INGESTION,
    RETRY_EMBEDDING,
    RETRY_INDEXING,
)

DLQ_TOPICS = (
    DLQ_INGESTION,
    DLQ_EMBEDDING,
    DLQ_INDEXING,
    DLQ_RAG,
)

ALL_TOPICS = (
    *INGESTION_TOPICS,
    RAG_LONG_QUERY,
    EVAL_BATCH,
    *RETRY_TOPICS,
    *DLQ_TOPICS,
)

TOPIC_TO_RETRY_TOPIC = {
    INGESTION_PARSE: RETRY_INGESTION,
    INGESTION_METADATA: RETRY_INGESTION,
    INGESTION_CHUNK: RETRY_INGESTION,
    INGESTION_EMBED: RETRY_EMBEDDING,
    INGESTION_INDEX: RETRY_INDEXING,
}

TOPIC_TO_DLQ_TOPIC = {
    INGESTION_PARSE: DLQ_INGESTION,
    INGESTION_METADATA: DLQ_INGESTION,
    INGESTION_CHUNK: DLQ_INGESTION,
    INGESTION_EMBED: DLQ_EMBEDDING,
    INGESTION_INDEX: DLQ_INDEXING,
    RAG_LONG_QUERY: DLQ_RAG,
}
